import type { Vault } from "~/types/vault";

export const mockVaults: Vault[] = [
  {
    id: "weth",
    name: "WETH",
    protocol: "COMPOUND",
    icon: "⟠",
    boost: false,
    atDeposit: "0.46978",
    atDepositUsd: "$877.36",
    now: "0.47484",
    nowUsd: "$1,815",
    yield: "0.00506",
    yieldUsd: "$10.36",
    pnl: "$938.38",
    pnlPercent: "106.95%",
    apy: "1.66%",
    apyPercent: "",
    dailyYield: "$0.08",
    tvl: "$41,522",
    apyValue: "2,680%",
    deposit: "0",
    lastHarvest: "2 hours ago",
  },
  {
    id: "usdt0",
    name: "USDT0",
    protocol: "COMPOUND",
    icon: "₮",
    boost: false,
    atDeposit: "1,099.99",
    atDepositUsd: "$1,100",
    now: "1,100.17",
    nowUsd: "$1,100",
    yield: "0.17149",
    yieldUsd: "$0.17",
    pnl: "$0.48",
    pnlPercent: "0.04%",
    apy: "3.54%",
    apyPercent: "",
    dailyYield: "$0.10",
    tvl: "$28,450",
    apyValue: "3.54%",
    deposit: "0",
    lastHarvest: "5 hours ago",
  },
  {
    id: "synd-weth-vlp",
    name: "SYND-WETH vLP",
    protocol: "AERODROME",
    icon: "🔄",
    boost: true,
    atDeposit: "0",
    atDepositUsd: "$0",
    now: "0",
    nowUsd: "$0",
    yield: "0",
    yieldUsd: "$0",
    pnl: "$0",
    pnlPercent: "0%",
    apy: "2,623%",
    apyPercent: "2,623%",
    dailyYield: "$0",
    tvl: "$41,522",
    apyValue: "2,680%",
    deposit: "0",
    lastHarvest: "2 hours ago",
  },
];
